# yaml-language-server: $schema=https://taskfile.dev
version: '3'

dotenv: ['.env']

includes:
  common: .task/common.yml

tasks:
  init:
    desc: "Initialisation complète de l'espace de travail"
    cmds:
      - git submodule update --init --recursive
      - echo "Environnement prêt."
